7
SamenaBasith/fe-nc-news pull request #7
Opened 2023-01-10 16:04 UTC by SamenaBasith

2023-01-10 16:38 UTC, lewispricey requested changes
Really great work on this Samena!

I'd recommend adding an error message to show the user if the like fails but overall really solid code :)

Please raise another PR once you've added in the error message.

2023-01-10 16:38 UTC, lewispricey commented on src/api.js
> +    const patchedBody = {
Really like that you've seperated the body out, keeps the code super clean!

2023-01-10 16:38 UTC, lewispricey commented on src/components/ArticleVotes.jsx
> +    function incVote(increment) {
Great re-use of the same function to increase and reduce votes

2023-01-10 16:38 UTC, lewispricey commented on src/components/ArticleVotes.jsx
> +        .catch(() => {
It would be good to let the user know with some sort of error message if the vote fails

2023-01-11 10:00 UTC, Dutton1990 commented
Yeah this looks great Samena nice job! 

If you like, you could implement only being able to vote once, but it's upto you and you don't need to send the PR again for us to check either way 😄 

You can merge this!

2023-01-11 10:16 UTC, merged